import { Box } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/navbar";
import ProductPageComponent from "../components/productPageComponent";

export const Product = () => {
  const { query } = useRouter();

  return (
    <>
      <Head>
        <title>Produkt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar></Navbar>
      </nav>
      <Box
        sx={{
          width: "100%",
          height: "100%",
          background: "url('/DC_bg.png') center repeat",
          backgroundSize: "110%",
        }}
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            width: "100%",
          }}
        >
          <Box
            sx={{
              display: "flex",
              flexDirection: "row",
              flexWrap: "wrap",
              justifyContent: "center",
              width: "80%",
              gap: "1rem",
            }}
          ></Box>
        </Box>
        <ProductPageComponent></ProductPageComponent>
      </Box>
    </>
  );
};

export default Product;
