import { Alert, Box } from "@mui/material";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/navbar";
import ProductPageComponent from "../components/productPageComponent";
import { useQuery, gql } from "@apollo/client";
import { Loader } from "../components/loader";
import { useSingleProductQuery } from "@/generated/graphql";

const Product: NextPage = () => {
  const { query } = useRouter();
  const { data, loading, error } = useSingleProductQuery({ skip: false });

  const generateProductComponent = (data: any) => {
    if (error) {
      return <Alert severity="error">{error.message}</Alert>;
    }
    if (!loading) {
      console.log(data);
      return (
        <>
          <ProductPageComponent
            key={data.singleProduct.id}
            name={data.singleProduct.name}
            description={data.singleProduct.description}
            image={data.singleProduct.image}
          ></ProductPageComponent>
        </>
      );
    } else {
      return <Loader></Loader>;
    }
  };

  return (
    <>
      <Head>
        <title>Produkt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar></Navbar>
      </nav>
      <Box
        sx={{
          width: "100%",
          height: "100%",
          background: "url('/DC_bg.png') center repeat",
          backgroundSize: "110%",
        }}
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            width: "100%",
          }}
        >
          <Box
            sx={{
              display: "flex",
              flexDirection: "row",
              flexWrap: "wrap",
              justifyContent: "center",
              width: "80%",
              gap: "1rem",
            }}
          ></Box>
        </Box>
        {generateProductComponent(data)}
      </Box>
    </>
  );
};

export default Product;
