import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Container } from "@mui/material";
import Navbar from "./components/navbar";
import MainMenu from "./components/mainMenu";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar></Navbar>
      </nav>
      <Box
        sx={{
          width: "100%",
          height: "100vh",
          background: "url('/DC_bg.png') center repeat",
          backgroundSize: "110%",
        }}
      >
        <Container maxWidth="sm">
          <Box
            sx={{
              display: "flex",
              justifyContent: "center",
              width: "100%",
            }}
          >
            <MainMenu></MainMenu>
          </Box>
        </Container>
        <Footer></Footer>
      </Box>
    </>
  );
}
