import { useProductsQuery } from "@/generated/graphql";
import { Alert, Box } from "@mui/material";
import Head from "next/head";
import Navbar from "./components/navbar";
import ProductComponent from "./components/productComponent";

export const Products = () => {
  const { data, loading, error } = useProductsQuery({ skip: false });

  const generateEmptyProducts = (data: any) => {
    if (error) {
      return <Alert severity="error">{error.message}</Alert>;
    }
    if (!loading) {
      return data.product.map((el: any) => (
        <ProductComponent
          key={el.id}
          id={el.id}
          title={el.name}
          description={el.description}
          image={el.image}
        ></ProductComponent>
      ));
    } else {
      return <p>Loading products...</p>;
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar></Navbar>
      </nav>
      <Box
        sx={{
          width: "100%",
          height: "100%",
          background: "url('/DC_bg.png') center repeat",
          backgroundSize: "110%",
        }}
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            width: "100%",
          }}
        >
          <Box
            sx={{
              display: "flex",
              flexDirection: "row",
              flexWrap: "wrap",
              justifyContent: "center",
              width: "80%",
              gap: "1rem",
            }}
          >
            {generateEmptyProducts(data)}
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default Products;
